In [36]:
import pandas as pd
import random


import string

In [37]:
MC1={
    'Substructure':['Piling', 'Foundation'],
    'Superstructure':['Frame and Slab']
    }

MC2={
    'Piling':['Permanent Pile'],
    'Foundation':['Raft Footing','Pile Cap','Column Base','Wall Footing','Substructure Wall','Substructure Column','Substructure Beam','Substructure Slab'],
    'Frame and Slab':['Structural Wall','RC Column','RC Beam','RC Slab','RC Staircase','RC Slab','Steel Beam','Steel Column','Steel Staircase']
    }
Item={
    'Permanent Pile':[['Type of Pile','Concrete Grade','Pile Diameter'],"Nos"],
    'Raft Footing':[['Concrete Grade'],"m3"],
    'Pile Cap':[['Concrete Grade'],"m3"],
    'Column Base':[['Concrete Grade'],"m3"],
    'Wall Footing':[['Concrete Grade'],"m3"],
    'Substructure Wall':[['Concrete Grade'],"m3"],
    'Substructure Column':[['Concrete Grade'],"m3"],
    'Substructure Beam':[['Concrete Grade'],"m3"],
    'Substructure Slab':[['Concrete Grade'],"m3"],
    'Structural Wall':[['Type of Construction','Concrete Grade','Type of Wall'],"m3"],
    'RC Column':[['Type of Construction','Concrete Grade'],"m3"],
    'RC Beam':[['Type of Construction','Concrete Grade','Post Tension'],"m3"],
    'RC Slab':[['Type of Construction','Concrete Grade','Post Tension'],"m3"],
    'RC Staircase':[['Type of Construction','Concrete Grade'],"m3"],
    'RC Slab':[['Type of Construction','Concrete Grade'],"m3"],
    'Steel Beam':[['Steel Grade','Steel Thickness'],"kg"],
    'Steel Column':[['Steel Grade','Steel Thickness'],"kg"],
    'Steel Staircase':[['Steel Grade','Steel Thickness'],"kg"]
    
}

Subcat={
    'Type of Pile':['Bored Pile','Spun Pile','Micro Pile'],
    'Pile Diameter':['200 mm','350mm','400'],
    'Concrete Grade':['G30','G40','35'],
    'Type of Construction':["Precast","Cast in-situ","Castinsitu"],
    'Type of Wall':["Lift Core Wall","Parapet Wall","Ramp Wall","Planter Wall"],
    'Post Tension':["Yes,1:35","80%","0.8","No",""],
    'Steel Grade':["S355","EN 10025 S275","BS4360 Grade 43A"],
    'Steel Thickness':["152 x 152 x 23 UC","5"]
}

In [38]:
columns=["Cost Code","Main Category 1","Main Category 2","Item","Sub Category 1","Sub Category 2","Sub Category 3","Unit","Rate","Description"]
# df=pd.DataFrame(columns=columns)
rows=[]
random.seed(10)
item_list=1000

for each in range(0,item_list):
    row=[]
    C_code=''.join(random.choices(string.ascii_uppercase + string.digits, k=random.randrange(6, 10)))
    
    MC1_df=random.choice(list(MC1))
    MC2_df=random.choice(MC1[MC1_df])
    Item_df=random.choice(MC2[MC2_df])
    row=[C_code,MC1_df,MC2_df,Item_df]
    
    for subcat_df in Item[Item_df][0]:
        row.append(random.choice(Subcat[subcat_df]))
    while len(row)<7:
        row.append("")
        
    unit=Item[Item_df][1]
    row.append(unit)
    
    rate=round(random.uniform(0.5, 40000), random.randrange(0, 4))
    row.append(rate)
    
    description=''.join(random.choices(string.ascii_uppercase + string.digits, k=random.randrange(6, 10)))+" "+''.join(random.choices(string.ascii_uppercase + string.digits, k=random.randrange(0, 3)))+" "+''.join(random.choices(string.ascii_uppercase + string.digits, k=random.randrange(0, 8)))
    row.append(description)

    rows.append(row)

In [39]:
df=pd.DataFrame(rows)
df.columns=columns
df=df.fillna('')
df.sort_values(["Main Category 1","Main Category 2","Item","Sub Category 1","Sub Category 3"],ignore_index=True,inplace=True)
df.to_csv("Sample Extracted Library.csv",index=False)

In [124]:
df

,Main Category 1,Main Category 2,Item,Sub Category 1,Sub Category 2,Sub Category 3,Unit,Quantity
0,Substructure,Foundation,Column Base,35,,,m3,5219.000
1,Substructure,Foundation,Column Base,35,,,m3,9917.160
2,Substructure,Foundation,Column Base,35,,,m3,7963.000
3,Substructure,Foundation,Column Base,35,,,m3,3987.000
4,Substructure,Foundation,Column Base,35,,,m3,1921.800
...,...,...,...,...,...,...,...,...
995,Superstructure,Frame and Slab,Structural Wall,Precast,G30,Planter Wall,m3,6161.000
996,Superstructure,Frame and Slab,Structural Wall,Precast,G40,Planter Wall,m3,3858.000
997,Superstructure,Frame and Slab,Structural Wall,Precast,G40,Ramp Wall,m3,9483.000
998,Superstructure,Frame and Slab,Structural Wall,Precast,35,Ramp Wall,m3,7310.920
999,Superstructure,Frame and Slab,Structural Wall,Precast,G40,Ramp Wall,m3,3135.593

In [118]:
df

,Main Category 1,Main Category 2,Item,Sub Category 1,Sub Category 2,Sub Category 3,Unit,Quantity
0,Substructure,Foundation,Column Base,35,,,m3,5219.000
1,Substructure,Foundation,Column Base,35,,,m3,9917.160
2,Substructure,Foundation,Column Base,35,,,m3,7963.000
3,Substructure,Foundation,Column Base,35,,,m3,3987.000
4,Substructure,Foundation,Column Base,35,,,m3,1921.800
...,...,...,...,...,...,...,...,...
995,Superstructure,Frame and Slab,Structural Wall,Precast,G30,Planter Wall,m3,6161.000
996,Superstructure,Frame and Slab,Structural Wall,Precast,G40,Planter Wall,m3,3858.000
997,Superstructure,Frame and Slab,Structural Wall,Precast,G40,Ramp Wall,m3,9483.000
998,Superstructure,Frame and Slab,Structural Wall,Precast,35,Ramp Wall,m3,7310.920
999,Superstructure,Frame and Slab,Structural Wall,Precast,G40,Ramp Wall,m3,3135.593

In [79]:
df

,MainCat1,MainCat2,Item,SubCat1,SubCat2,SubCat3,Unit,Quantity
0,Substructure,Foundation,Substrcture Slab,35,m3,0.64,None,NaN
1,Superstructure,Frame and Slab,RC Staircase,Castinsitu,G30,m3,0.83,NaN
2,Superstructure,Frame and Slab,RC Column,Precast,35,m3,9.97,NaN
3,Substructure,Foundation,Column Base,35,m3,3.87,None,NaN
4,Superstructure,Frame and Slab,RC Staircase,Cast in-situ,G30,m3,7.02,NaN
5,Superstructure,Frame and Slab,Steel Column,S355,5,kg,6.33,NaN
6,Substructure,Piling,Permamnent Pile,Bored Pile,G30,350mm,Nos,5.6
7,Substructure,Foundation,Substrcture Slab,G40,m3,4.96,None,NaN
8,Superstructure,Frame and Slab,RC Slab,Cast in-situ,G30,m3,0.85,NaN
9,Superstructure,Frame and Slab,RC Column,Castinsitu,G30,m3,1.92,NaN

In [49]:
df2=pd.DataFrame(row)

In [50]:
df2

                0               1                2
0  Superstructure  Frame and Slab       Steel Beam
1  Superstructure  Frame and Slab     Steel Column
2    Substructure      Foundation         Pile Cap
3  Superstructure  Frame and Slab          RC Beam
4    Substructure      Foundation     Wall Footing
5  Superstructure  Frame and Slab       Steel Beam
6    Substructure          Piling  Permamnent Pile
7  Superstructure  Frame and Slab  Structural Wall
8  Superstructure  Frame and Slab          RC Slab
9    Substructure          Piling  Permamnent Pile

In [23]:
for each in MC1:
    for each2 in MC1[each]:
        for each3 in MC2[each2]:
            for each4 in Item[each3][0]:
                print(Subcat[each4])

['Bored Pile', 'Spun Pile', 'Micro Pile']
['G30', 'G40', '35']
['200 mm', '350mm', '400']
['G30', 'G40', '35']
['G30', 'G40', '35']
['G30', 'G40', '35']
['G30', 'G40', '35']
['G30', 'G40', '35']
['G30', 'G40', '35']
['G30', 'G40', '35']
['G30', 'G40', '35']
['Precast', 'Cast in-situ', 'Castinsitu', ' ', '']
['G30', 'G40', '35']
['Lift Core Wall', 'Parapet Wall', 'Ramp Wall', 'Planter Wall', '']
['Precast', 'Cast in-situ', 'Castinsitu', ' ', '']
['G30', 'G40', '35']
['Precast', 'Cast in-situ', 'Castinsitu', ' ', '']
['G30', 'G40', '35']
['Yes,1:35', '80%', '0.8', 'No', '']
['Precast', 'Cast in-situ', 'Castinsitu', ' ', '']
['G30', 'G40', '35']
['Precast', 'Cast in-situ', 'Castinsitu', ' ', '']
['G30', 'G40', '35']
['Precast', 'Cast in-situ', 'Castinsitu', ' ', '']
['G30', 'G40', '35']
['S355', 'EN 10025 S275', 'BS4360 Grade 43A']
['152 x 152 x 23 UC', '5']
['S355', 'EN 10025 S275', 'BS4360 Grade 43A']
['152 x 152 x 23 UC', '5']
['S355', 'EN 10025 S275', 'BS4360 Grade 43A']
['152 x 152 x 23 UC', '5']